# Generated by Django 4.2.13 on 2024-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query_Builder', '0006_parseddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='current_employee_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='total_employee_estimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='year_founded',
            field=models.IntegerField(default=0),
        ),
    ]
